### ISSUE TITLE
I don't mean to disturb you. I'd like to ask for some advice.

### ISSUE THREAD

**Issue by wangkai123456** [talmand/demo-transitions#1]
Recent learning createjs See you a previous project, I feel very good, I hope to give some advice. Thank you very much. My mailbox is 1205669217@qq.com. If it's convenient, I hope I can keep in touch with each other. Thank.

**Comment by talmand** [comment]
I'm sorry, I don't really work in createjs these days. I'm rather out-of-date on that subject.

**Comment by wangkai123456** [comment]
You are very good. I hope you can get help.
